package geekwork.spring.bucks.mapper;

import geekwork.spring.bucks.model.OrderCoffee;
import geekwork.spring.bucks.model.OrderCoffeeExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface OrderCoffeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ORDER_COFFEE
     *
     * @mbg.generated Sun Nov 27 17:24:12 GMT+08:00 2022
     */
    long countByExample(OrderCoffeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ORDER_COFFEE
     *
     * @mbg.generated Sun Nov 27 17:24:12 GMT+08:00 2022
     */
    int deleteByExample(OrderCoffeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ORDER_COFFEE
     *
     * @mbg.generated Sun Nov 27 17:24:12 GMT+08:00 2022
     */
    @Insert({
        "insert into T_ORDER_COFFEE (COFFEE_ORDER_ID, ITEMS_ID)",
        "values (#{coffeeOrderId,jdbcType=BIGINT}, #{itemsId,jdbcType=BIGINT})"
    })
    int insert(OrderCoffee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ORDER_COFFEE
     *
     * @mbg.generated Sun Nov 27 17:24:12 GMT+08:00 2022
     */
    int insertSelective(OrderCoffee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ORDER_COFFEE
     *
     * @mbg.generated Sun Nov 27 17:24:12 GMT+08:00 2022
     */
    List<OrderCoffee> selectByExampleWithRowbounds(OrderCoffeeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ORDER_COFFEE
     *
     * @mbg.generated Sun Nov 27 17:24:12 GMT+08:00 2022
     */
    List<OrderCoffee> selectByExample(OrderCoffeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ORDER_COFFEE
     *
     * @mbg.generated Sun Nov 27 17:24:12 GMT+08:00 2022
     */
    int updateByExampleSelective(@Param("record") OrderCoffee record, @Param("example") OrderCoffeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ORDER_COFFEE
     *
     * @mbg.generated Sun Nov 27 17:24:12 GMT+08:00 2022
     */
    int updateByExample(@Param("record") OrderCoffee record, @Param("example") OrderCoffeeExample example);
}